// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKzT1NXQF-4zcIEIz4587KhRH1P62gadE',
    appId: '1:300931087537:android:593230827c8a400ba27690',
    messagingSenderId: '300931087537',
    projectId: 'stylish-2f950',
    storageBucket: 'stylish-2f950.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkrLFaE8nvK75O-OrOliXZQGaPZb9XpC0',
    appId: '1:300931087537:ios:c9e26fbc6ea29887a27690',
    messagingSenderId: '300931087537',
    projectId: 'stylish-2f950',
    storageBucket: 'stylish-2f950.firebasestorage.app',
    androidClientId: '300931087537-7o479a9e1r7aol8vq5jhj1lupf427v62.apps.googleusercontent.com',
    iosClientId: '300931087537-nlidti7pfu1kkljl2gbhfgmhkm9d6jtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylish',
  );

}