// ============================================================
// scripts/seed_firestore.js
// 🔥 FIRESTORE SEEDER - E-COMMERCE APP (NODE.JS)
// ============================================================

const admin = require('firebase-admin');

// ============================================================
// 1. إعدادات Firebase (استخدم المفتاح بتاعك مباشرة)
// ============================================================
const serviceAccount = {
  type: "service_account",
  project_id: "stylish-2f950",
  private_key_id: "f82bd027a078b907a42b1b77aa1f4493a6af05f6",
  private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDYbyWmBLavW3DF\nNbWGVwMYEVyhbVkC2OEqN1Q7mZRlzShztuAdI0QX1bz/ziJUsHTyY/iVnEdq+anH\nwQg/n3z3BYhLkGjJUiD+IDWP2nfXy4Aj1EvxjE6YqhfIlX+X9KlGxId201/41ftZ\nrMEKgWBSDCKO5uxTLGhR7SA7w1bTxBT/8Vxf4/bLEzhovuWTCiZWOJQkEWTnpBQR\nFxb+rADLl6zijicz2ux449yqXD88HMh5bF2/koGz71W7Ou8nvmfjxeK5aqYulHsl\nZpzu/ZqIKNY7VOBq5bYtPF774tgzVRXvcn6rAcz6qWLP4KJmXOw85+QYcC9GkfTs\nfdAXA/z3AgMBAAECggEANKBmD6XCxAXgeFt0bZt3uaDzHJ9pjtsseObmOO3BmzVU\n+joD6aHbG06R+8NkLqKPdSbg2YQcC4N0iIlD17CQosH6H6GYESfCtPgg/f8Zt+OY\nH14uLyg2LkHhsZjEYy8PABGmfLqt8eQaD3aFo+fMg3bG6md1HE5GeXFGrrFzSd9H\n3Qly/Qx+1BFrGpXb0gmsNMNImgqh1qPA8bemYqqWl+I5/CnjMhsGk8gsXmJ9PfRQ\n/HsVDJmOKGuD4wNP/RO5IWgKIdYFDrpjPy97CgVlc3KinmiSVMsejSuO6eX4pejr\nQK2rv5Pp/qcFLFixopYizOTzWSSJMNyg2w5xZxV4cQKBgQDvWfo07JNAXuZ2/gzg\nFief/bUyQdPF27RAZKJcthStJeHE7Fkca0lioXt21mY7+dMFAGT3y/QmArZ6fR+s\nlyeJX06PkD36FigJyA/f/7tKnfpR2kdhaI1MtHYBgLgmJIEO5oIG3Nex+0nQXcWT\nrEyWH31qevbYbNc0khx1twpYMQKBgQDnfRd3zGL435ientWM19f5b0sPvUm6XlDA\nkrf9OnZsBJumfdgRz9murjednrVl8heHrthBdzQPwSnhDr6O7CGHY1yoHw8t1qW2\nz7ddLCtrmto/krKjVXDt568ohCxE5lgNmIcDFTNC3oVJcQoeFpetACyMrrirUhbv\nffun3OOFpwKBgBPD9mmQb8iNDbMd36pRqgwIQ4JW9UoNjqESrmXBk4uI6U/9xI4Y\nPgMrGqsBoYeqZcav9aaQ7SSGbNNIqejywo0Rlcc9PiD822mTX9w7nhfXW+iOgf6F\nR8Xh0SzmmE5uDUpRtsMiUZ2dBsdyNvKu89Qh3ZWBegj9U/g/aKI/71bBAoGAQ+Rf\nPqZ2HJHPfC4PabhgQmrOs/YLKprAykn9pkpAMxwC3oioF0lDicTeM385qoWfOw8f\no8unPDul4bjmUJqWltOgeDprxEDg50XyfGQY8/09p0mKFPdZIJ1DtPlW1npMNuiW\nKGROXX1P0CNUGVD8+SNE7ZnM1YpE6cakSS4ymJ8CgYEAwFGkkVmLsTn5NHG60tsR\ndjRt1eJuRozwdjvbcI/TSgWfREqBHbWirHl5GIOJ/iJoFkut5M9YnWkFQTTpyMKw\ncOJInNfKM2K79Kld2OwmfLmQPUpUSwpLN1F8q+Z4D8Pdk9SEsyo6DTdpRR1jNK46\nZDc3Gb0BeDMe1wlrkD2K5Xs=\n-----END PRIVATE KEY-----\n",
  client_email: "firebase-adminsdk-fbsvc@stylish-2f950.iam.gserviceaccount.com",
  client_id: "101064687625422080627"
};

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  projectId: 'stylish-2f950'
});

const db = admin.firestore();

// ============================================================
// 2. دوال رفع البيانات
// ============================================================

async function seedUsers() {
  const users = [
    {
      uid: 'user_001',
      email: 'john.doe@example.com',
      name: 'John Doe',
      phone: '+1 555 123 4567',
      profileImage: 'https://randomuser.me/api/portraits/women/44.jpg',
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    }
  ];

  const batch = db.batch();
  for (const user of users) {
    const ref = db.collection('users').doc(user.uid);
    batch.set(ref, user);
  }
  await batch.commit();
  console.log(`✅ Users seeded (${users.length})`);
}

async function seedCategories() {
  const categories = [
    {
      id: 'cat_beauty',
      name: 'Beauty',
      image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
      isActive: true,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'cat_fashion',
      name: 'Fashion',
      image: 'https://images.unsplash.com/photo-1445205170230-053b83016050',
      isActive: true,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'cat_kids',
      name: 'Kids',
      image: 'https://images.unsplash.com/photo-1519241047957-be31d7379a5d',
      isActive: true,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'cat_mens',
      name: 'Mens',
      image: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59',
      isActive: true,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'cat_womens',
      name: 'Womens',
      image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446',
      isActive: true,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
  ];

  const batch = db.batch();
  for (const c of categories) {
    const ref = db.collection('categories').doc(c.id);
    batch.set(ref, c);
  }
  await batch.commit();
  console.log(`✅ Categories seeded (${categories.length})`);
}

async function seedProducts() {
  const products = [

    // ─────────────────────────────────────────────
    // 🔥 DEAL OF THE DAY
    // ─────────────────────────────────────────────
    {
      id: 'prod_dotd_001',
      name: 'Women Printed Floral Kurta',
      brand: 'Libas',
      categoryId: 'cat_womens',
      price: 2499,
      salePrice: 1500,
      discountPercentage: 40,
      description: 'Elegant cotton printed kurta with 3/4 sleeves, perfect for summer outings.',
      image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800',
      rating: 4.5,
      reviewCount: 56890,
      inStock: true,
      isDealOfTheDay: true,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_dotd_002',
      name: "HRX Men's High-Top Sneakers",
      brand: 'HRX',
      categoryId: 'cat_mens',
      price: 4999,
      salePrice: 2499,
      discountPercentage: 50,
      description: 'Durable and stylish high-top sneakers with ergonomic sole for maximum comfort.',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800',
      rating: 4.5,
      reviewCount: 344567,
      inStock: true,
      isDealOfTheDay: true,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_dotd_003',
      name: 'Premium Leather Tote Bag',
      brand: 'Coach',
      categoryId: 'cat_womens',
      price: 6999,
      salePrice: 3499,
      discountPercentage: 50,
      description: 'Full-grain leather tote with gold hardware, fits a 13" laptop. Timeless and functional.',
      image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=800',
      rating: 4.8,
      reviewCount: 12400,
      inStock: true,
      isDealOfTheDay: true,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_dotd_004',
      name: 'Running Track Pants',
      brand: 'Adidas',
      categoryId: 'cat_mens',
      price: 3200,
      salePrice: 1599,
      discountPercentage: 50,
      description: 'Lightweight moisture-wicking track pants with zip pockets and tapered fit.',
      image: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&q=80&w=800',
      rating: 4.3,
      reviewCount: 9870,
      inStock: true,
      isDealOfTheDay: true,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },

    // ─────────────────────────────────────────────
    // 📈 TRENDING PRODUCTS
    // ─────────────────────────────────────────────
    {
      id: 'prod_trend_001',
      name: 'IWC Pilot Chronograph Watch',
      brand: 'IWC',
      categoryId: 'cat_fashion',
      price: 1599,
      salePrice: 650,
      discountPercentage: 60,
      description: 'Premium stainless steel chronograph with a sleek leather strap.',
      image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800',
      rating: 4.9,
      reviewCount: 850,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: true,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_trend_002',
      name: 'Labbin Classic White Sneakers',
      brand: 'Labbin',
      categoryId: 'cat_mens',
      price: 1250,
      salePrice: 650,
      discountPercentage: 50,
      description: 'Minimalist all-white leather sneakers for a clean urban look.',
      image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&q=80&w=800',
      rating: 4.2,
      reviewCount: 450,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: true,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_trend_003',
      name: 'Mammon Luxury Handbag Set',
      brand: 'Mammon',
      categoryId: 'cat_womens',
      price: 1999,
      salePrice: 750,
      discountPercentage: 62,
      description: 'A set of 3 premium leather handbags for work and evening events.',
      image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?auto=format&fit=crop&q=80&w=800',
      rating: 4.7,
      reviewCount: 120,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: true,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_trend_004',
      name: 'Oversized Graphic Hoodie',
      brand: 'H&M',
      categoryId: 'cat_fashion',
      price: 2200,
      salePrice: 1100,
      discountPercentage: 50,
      description: 'Ultra-soft fleece hoodie with bold front print. Available in multiple colorways.',
      image: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?auto=format&fit=crop&q=80&w=800',
      rating: 4.4,
      reviewCount: 3760,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: true,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_trend_005',
      name: 'Cat-Eye Sunglasses',
      brand: 'Ray-Ban',
      categoryId: 'cat_womens',
      price: 3500,
      salePrice: 1999,
      discountPercentage: 43,
      description: 'Retro-inspired cat-eye frame with UV400 polarized lenses in tortoise shell.',
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=800',
      rating: 4.6,
      reviewCount: 5230,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: true,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_trend_006',
      name: 'Slim Fit Chino Trousers',
      brand: 'Zara',
      categoryId: 'cat_mens',
      price: 2800,
      salePrice: 1400,
      discountPercentage: 50,
      description: 'Stretch cotton chino with slim-tapered leg in earthy khaki. Office-to-weekend versatility.',
      image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&q=80&w=800',
      rating: 4.3,
      reviewCount: 2180,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: true,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },

    // ─────────────────────────────────────────────
    // 🆕 NEW ARRIVALS
    // ─────────────────────────────────────────────
    {
      id: 'prod_new_001',
      name: 'Denim Trucker Jacket',
      brand: 'Levis',
      categoryId: 'cat_fashion',
      price: 3500,
      salePrice: 2100,
      discountPercentage: 40,
      description: 'Classic blue denim jacket with vintage wash and metal buttons.',
      image: 'https://images.unsplash.com/photo-1576905341939-4290b99619c9?auto=format&fit=crop&q=80&w=800',
      rating: 4.8,
      reviewCount: 95,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: true,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_new_002',
      name: 'Emerald Silk Evening Dress',
      brand: 'Zara',
      categoryId: 'cat_womens',
      price: 4500,
      salePrice: 2800,
      discountPercentage: 38,
      description: 'Luxurious silk wrap dress in emerald green for evening parties.',
      image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=800',
      rating: 4.6,
      reviewCount: 210,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: true,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_new_003',
      name: 'Linen Cuban Collar Shirt',
      brand: 'H&M',
      categoryId: 'cat_mens',
      price: 1800,
      salePrice: 1100,
      discountPercentage: 39,
      description: 'Breathable linen shirt with a relaxed cuban collar in light beige.',
      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=800',
      rating: 4.4,
      reviewCount: 340,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: true,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_new_004',
      name: 'Floral Maxi Sundress',
      brand: 'Mango',
      categoryId: 'cat_womens',
      price: 3200,
      salePrice: 1900,
      discountPercentage: 41,
      description: 'Flowing viscose maxi dress with all-over floral print and adjustable straps.',
      image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&q=80&w=800',
      rating: 4.5,
      reviewCount: 178,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: true,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_new_005',
      name: 'Ribbed Knit Polo Shirt',
      brand: 'Ralph Lauren',
      categoryId: 'cat_mens',
      price: 5500,
      salePrice: 3300,
      discountPercentage: 40,
      description: 'Cotton piqué polo with ribbed collar and signature embroidered logo.',
      image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&q=80&w=800',
      rating: 4.7,
      reviewCount: 640,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: true,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_new_006',
      name: 'Platform Chelsea Boots',
      brand: 'Steve Madden',
      categoryId: 'cat_womens',
      price: 5800,
      salePrice: 3499,
      discountPercentage: 40,
      description: 'Faux-leather chelsea boots with chunky platform sole and elastic side panels.',
      image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&q=80&w=800',
      rating: 4.5,
      reviewCount: 422,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: true,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_new_007',
      name: 'Cargo Utility Vest',
      brand: 'Uniqlo',
      categoryId: 'cat_mens',
      price: 2500,
      salePrice: 1499,
      discountPercentage: 40,
      description: 'Multi-pocket nylon utility vest, lightweight and water-resistant. Great for travel.',
      image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800',
      rating: 4.6,
      reviewCount: 310,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: true,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },

    // ─────────────────────────────────────────────
    // 💰 SPONSORED
    // ─────────────────────────────────────────────
    {
      id: 'prod_spon_001',
      name: 'Tan Suede Boat Shoes',
      brand: 'Red Tape',
      categoryId: 'cat_mens',
      price: 4000,
      salePrice: 2000,
      discountPercentage: 50,
      description: 'Premium tan suede loafers with white rubber soles for a nautical look.',
      image: 'https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&q=80&w=800',
      rating: 4.8,
      reviewCount: 15400,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: true,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_spon_002',
      name: 'Gold Layered Necklace Set',
      brand: 'Accessorize',
      categoryId: 'cat_womens',
      price: 1800,
      salePrice: 999,
      discountPercentage: 44,
      description: 'Set of 3 dainty gold-plated necklaces in varying lengths for a layered look.',
      image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800',
      rating: 4.6,
      reviewCount: 8750,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: true,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_spon_003',
      name: 'Structured Blazer',
      brand: 'Massimo Dutti',
      categoryId: 'cat_womens',
      price: 7500,
      salePrice: 4200,
      discountPercentage: 44,
      description: 'Single-breasted tailored blazer in camel wool blend. A wardrobe investment piece.',
      image: 'https://images.unsplash.com/photo-1594938298603-c8148c4bea4c?auto=format&fit=crop&q=80&w=800',
      rating: 4.9,
      reviewCount: 2100,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: true,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },

    // ─────────────────────────────────────────────
    // 👶 KIDS
    // ─────────────────────────────────────────────
    {
      id: 'prod_kids_001',
      name: 'Yellow Cotton Dungarees',
      brand: 'MiniClub',
      categoryId: 'cat_kids',
      price: 1200,
      salePrice: 799,
      discountPercentage: 33,
      description: 'Soft organic cotton overalls for babies and toddlers.',
      image: 'https://images.unsplash.com/photo-1519234221711-5bb9793fb0a4?auto=format&fit=crop&q=80&w=800',
      rating: 4.9,
      reviewCount: 215,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_kids_002',
      name: "Dinosaur Print Pyjama Set",
      brand: 'Marks & Spencer',
      categoryId: 'cat_kids',
      price: 999,
      salePrice: 599,
      discountPercentage: 40,
      description: 'Cozy brushed-cotton pyjama set with all-over dino print. Ages 2–8.',
      image: 'https://images.unsplash.com/photo-1471286374628-7adfa9eb1b34?auto=format&fit=crop&q=80&w=800',
      rating: 4.8,
      reviewCount: 560,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_kids_003',
      name: 'Girls Tulle Party Dress',
      brand: 'Next',
      categoryId: 'cat_kids',
      price: 1800,
      salePrice: 1099,
      discountPercentage: 39,
      description: 'Sparkly sequin bodice with layered tulle skirt, perfect for birthdays and parties.',
      image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&q=80&w=800',
      rating: 4.7,
      reviewCount: 384,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_kids_004',
      name: 'Boys Denim Jacket',
      brand: 'Gap Kids',
      categoryId: 'cat_kids',
      price: 2200,
      salePrice: 1299,
      discountPercentage: 41,
      description: 'Rugged denim jacket with patch pockets and adjustable waist tabs. Ages 3–12.',
      image: 'https://images.unsplash.com/photo-1555009393-f20bdb245c4d?auto=format&fit=crop&q=80&w=800',
      rating: 4.6,
      reviewCount: 279,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_kids_005',
      name: 'Light-Up Running Shoes',
      brand: 'Skechers',
      categoryId: 'cat_kids',
      price: 2500,
      salePrice: 1499,
      discountPercentage: 40,
      description: 'LED light-up sneakers with easy hook-and-loop closure. Non-slip rubber outsole.',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800',
      rating: 4.9,
      reviewCount: 1120,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },

    // ─────────────────────────────────────────────
    // 💄 BEAUTY
    // ─────────────────────────────────────────────
    {
      id: 'prod_beauty_001',
      name: 'Matte Liquid Lipstick Set',
      brand: 'MAC',
      categoryId: 'cat_beauty',
      price: 2500,
      salePrice: 1800,
      discountPercentage: 28,
      description: 'Long-lasting, smudge-proof matte lipstick in 5 iconic shades.',
      image: 'https://images.unsplash.com/photo-1586776977607-310e9c725c37?auto=format&fit=crop&q=80&w=800',
      rating: 4.7,
      reviewCount: 3200,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_beauty_002',
      name: 'Vitamin C Brightening Serum',
      brand: "The Ordinary",
      categoryId: 'cat_beauty',
      price: 1800,
      salePrice: 1199,
      discountPercentage: 33,
      description: '15% ascorbic acid serum that visibly brightens skin and reduces dark spots in 4 weeks.',
      image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800',
      rating: 4.8,
      reviewCount: 14500,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_beauty_003',
      name: 'Rose Quartz Facial Roller',
      brand: 'Mount Lai',
      categoryId: 'cat_beauty',
      price: 1500,
      salePrice: 899,
      discountPercentage: 40,
      description: 'Genuine rose quartz facial roller to depuff, boost circulation, and enhance glow.',
      image: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?auto=format&fit=crop&q=80&w=800',
      rating: 4.6,
      reviewCount: 6780,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_beauty_004',
      name: 'Eyeshadow Palette - Nude Tones',
      brand: 'Urban Decay',
      categoryId: 'cat_beauty',
      price: 4500,
      salePrice: 2799,
      discountPercentage: 38,
      description: '12-shade neutral eyeshadow palette with matte, shimmer, and glitter finishes.',
      image: 'https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?auto=format&fit=crop&q=80&w=800',
      rating: 4.9,
      reviewCount: 8900,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_beauty_005',
      name: 'Hyaluronic Acid Moisturizer',
      brand: 'Neutrogena',
      categoryId: 'cat_beauty',
      price: 1200,
      salePrice: 799,
      discountPercentage: 33,
      description: 'Lightweight gel-cream that delivers 48-hour hydration with triple hyaluronic acid.',
      image: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800',
      rating: 4.7,
      reviewCount: 22100,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_beauty_006',
      name: 'Perfume - Floral Oud 100ml',
      brand: 'Jo Malone',
      categoryId: 'cat_beauty',
      price: 12000,
      salePrice: 8499,
      discountPercentage: 29,
      description: 'An intoxicating blend of rose, oud, and amber. Long-lasting luxury fragrance.',
      image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800',
      rating: 4.9,
      reviewCount: 5600,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },

    // ─────────────────────────────────────────────
    // 👗 FASHION (misc.)
    // ─────────────────────────────────────────────
    {
      id: 'prod_fashion_001',
      name: 'Black Leather Biker Jacket',
      brand: 'AllSaints',
      categoryId: 'cat_fashion',
      price: 8000,
      salePrice: 4500,
      discountPercentage: 44,
      description: 'Genuine sheepskin leather jacket with asymmetrical zipper.',
      image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=800',
      rating: 4.9,
      reviewCount: 450,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_fashion_002',
      name: 'Wide-Leg Tailored Trousers',
      brand: 'COS',
      categoryId: 'cat_fashion',
      price: 4200,
      salePrice: 2499,
      discountPercentage: 40,
      description: 'High-waist wide-leg trousers in premium crepe fabric. Minimalist and elegant.',
      image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=800',
      rating: 4.6,
      reviewCount: 1340,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_fashion_003',
      name: 'Colorblock Knit Sweater',
      brand: 'Zara',
      categoryId: 'cat_fashion',
      price: 3000,
      salePrice: 1799,
      discountPercentage: 40,
      description: 'Relaxed oversized knit sweater in bold color-block panels. 100% recycled cotton.',
      image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&q=80&w=800',
      rating: 4.5,
      reviewCount: 890,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_fashion_004',
      name: 'Bucket Hat - Canvas',
      brand: 'New Era',
      categoryId: 'cat_fashion',
      price: 1200,
      salePrice: 699,
      discountPercentage: 42,
      description: 'Reversible canvas bucket hat with adjustable drawstring, UV50+ protection.',
      image: 'https://images.unsplash.com/photo-1556306535-38febf6782e7?auto=format&fit=crop&q=80&w=800',
      rating: 4.3,
      reviewCount: 4200,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },

    // ─────────────────────────────────────────────
    // 👠 WOMENS (misc.)
    // ─────────────────────────────────────────────
    {
      id: 'prod_womens_001',
      name: 'Satin Slip Midi Skirt',
      brand: 'ASOS',
      categoryId: 'cat_womens',
      price: 2200,
      salePrice: 1299,
      discountPercentage: 41,
      description: 'Bias-cut satin midi skirt with subtle sheen and elasticated waistband.',
      image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&q=80&w=800',
      rating: 4.5,
      reviewCount: 760,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_womens_002',
      name: 'Strappy Heeled Sandals',
      brand: 'Aldo',
      categoryId: 'cat_womens',
      price: 3800,
      salePrice: 2199,
      discountPercentage: 42,
      description: 'Barely-there strappy heels in nude patent leather. 3-inch stiletto heel.',
      image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=800',
      rating: 4.4,
      reviewCount: 1890,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_womens_003',
      name: 'Ribbed Crop Tank Top',
      brand: 'Skims',
      categoryId: 'cat_womens',
      price: 1500,
      salePrice: 899,
      discountPercentage: 40,
      description: 'Second-skin ribbed tank with built-in support. Available in 12 shades.',
      image: 'https://images.unsplash.com/photo-1503342394128-c104d54dba01?auto=format&fit=crop&q=80&w=800',
      rating: 4.7,
      reviewCount: 9870,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },

    // ─────────────────────────────────────────────
    // 👔 MENS (misc.)
    // ─────────────────────────────────────────────
    {
      id: 'prod_mens_001',
      name: 'Oxford Dress Shirt - White',
      brand: 'Charles Tyrwhitt',
      categoryId: 'cat_mens',
      price: 3500,
      salePrice: 1999,
      discountPercentage: 43,
      description: 'Non-iron slim-fit Oxford shirt in crisp white. Perfect for formal and smart-casual.',
      image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800',
      rating: 4.8,
      reviewCount: 5400,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_mens_002',
      name: 'Desert Suede Chukka Boots',
      brand: 'Clarks',
      categoryId: 'cat_mens',
      price: 5500,
      salePrice: 3299,
      discountPercentage: 40,
      description: 'Iconic suede chukka boots with crepe sole. A timeless wardrobe essential.',
      image: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&q=80&w=800',
      rating: 4.7,
      reviewCount: 3200,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_mens_003',
      name: 'Merino Wool Crewneck Sweater',
      brand: 'Uniqlo',
      categoryId: 'cat_mens',
      price: 2999,
      salePrice: 1799,
      discountPercentage: 40,
      description: 'Fine-gauge merino wool sweater in navy. Lightweight, warm, and non-itchy.',
      image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&q=80&w=800',
      rating: 4.8,
      reviewCount: 7800,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
    {
      id: 'prod_mens_004',
      name: 'Leather Bifold Wallet',
      brand: 'Tommy Hilfiger',
      categoryId: 'cat_mens',
      price: 2000,
      salePrice: 1199,
      discountPercentage: 40,
      description: 'Slim pebbled-leather bifold with 6 card slots, ID window, and bill compartment.',
      image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800',
      rating: 4.6,
      reviewCount: 4100,
      inStock: true,
      isDealOfTheDay: false,
      isTrending: false,
      isNewArrival: false,
      isSponsored: false,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    },
  ];

  // Firestore batch limit is 500 writes; split into chunks of 400 to be safe
  const chunkSize = 400;
  for (let i = 0; i < products.length; i += chunkSize) {
    const chunk = products.slice(i, i + chunkSize);
    const batch = db.batch();
    for (const p of chunk) {
      const ref = db.collection('products').doc(p.id);
      batch.set(ref, p);
    }
    await batch.commit();
  }

  console.log(`✅ Products seeded (${products.length})`);
}

async function seedOrders() {
  const orders = [
    {
      id: 'ord_001',
      userId: 'user_001',
      orderNumber: 'ORD-1001',
      items: [
        {
          productId: 'prod_dotd_001',
          productName: 'Women Printed Kurta',
          price: 1500,
          quantity: 1,
        }
      ],
      subtotal: 1500,
      total: 1500,
      status: 'delivered',
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    }
  ];

  const batch = db.batch();
  for (const o of orders) {
    const ref = db.collection('orders').doc(o.id);
    batch.set(ref, o);
  }
  await batch.commit();
  console.log(`✅ Orders seeded (${orders.length})`);
}

// ============================================================
// 3. الدالة الرئيسية
// ============================================================
async function seed() {
  console.log('🌱 Starting Firestore seeding...\n');

  await seedUsers();
  await seedCategories();
  await seedProducts();
  await seedOrders();

  console.log('\n🎉 Seeding completed successfully!');
}

seed().catch(console.error);